### ISSUE TITLE
Failed to start on Linux (CentOS) due to iconbitmap call

### ISSUE THREAD

**Issue by kinow** [crxguy52/serialplot#4]
Seems to be an issue with my OS, thus included it in the title. git-clone'd the project, using Anaconda Python 2 or Anaconda Python 3, and pip install pyserial (already had other libs), I get the following error.

```
[kinoshitabd@localhost serialplot]$ python serialplot.py 
Traceback (most recent call last):
  File "serialplot.py", line 35, in <module>
    root.iconbitmap(default=graphicon)
  File "/home/kinoshitabd/Development/python/anaconda3/lib/python3.5/tkinter/__init__.py", line 1713, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
```

Commenting out `root.iconbitmap(default='graphs.ico')` the window is displayed (though empty and really small).

**Comment by kinow** [comment]
Related I think http://stackoverflow.com/questions/20860325/python-3-tkinter-iconbitmap-error-in-ubuntu

**Comment by kinow** [comment]
OS: CentOS Linux release 7.2.1511 (Core) 
Python: 
- Python 3.5.1 :: Anaconda 2.4.1 (64-bit)
- Python 2.7.11 :: Anaconda 2.5.0 (64-bit)

**Comment by crxguy52** [comment]
After you commented out the icon line, you said it still didn't run? Any errors?

I coded this mostly for Windows, so there may be some Linux specific issues I haven't run into. If you find a solution, please let me know.

Are you running it with Python 2.7?

**Comment by kinow** [comment]
Wow, super fast response @crxguy52 

I'm reading the code to see what else I need to do to see the complete window. At the moment I see something like a super tiny window. It's the size of the blinking cursor in the command line. I assume it is because I don't have anything connected to the serial port, and the application is not getting any data.

I tried both Python 2.7 and Python 3.5 (updated ticket above)

**Comment by crxguy52** [comment]
The configuration window should still come up and allow you to select options. My guess is that since Windows and Linux handle COM ports differently, it's getting hung up when it tries to populate them for the first time. Try commenting out the part in COMbox that fetches the available COM ports

I'm excited someone is using it!

**Comment by kinow** [comment]
Cool, I'm trying to emulate a serial port with `socat` in linux (if that works will send a pull request for documentation :grin: ).

A researcher found your project and sent it to a few other researchers and CC'ed me. I work with NIWA, where we have similar projects to ingest data from serial ports for environmental data collecting.

**Comment by crxguy52** [comment]
That's cool! I'm a grad student myself (MechE), so I can relate. This was my first big software project, so there might be some rookie mistakes in my code.

**Comment by kinow** [comment]
Almost there. Faked some serial ports, and the method to retrieve com ports seems to be working.

The window is still super small. But Changing this

```
root.resizable(width=False, height=False)
```

to
    root.resizable(width=True, height=True)

Allowed me to resize and confirm everything seems to be there (buttons, text, etc). There's something wrong with the window sizing (at least with Anaconda Python 3 + CentOS).

**Comment by crxguy52** [comment]
Closing this issue since the bugs seemed to be worked out. I verified your pull requests didn't break anything on Windows.
